COMPONENT=NodoAnclaAppC
CFLAGS += -I$(TOSDIR)/lib/printf
CFLAGS += -I$(TOSDIR)/platforms/telosa/chips/s1087 
CFLAGS += -I$(TOSDIR)/platforms/telosa/chips/s10871 
CFLAGS += -I$(TOSDIR)/platforms/telosa/chips/sht11
include $(MAKERULES)

